- name: read network ipv6 from file csv
  set_fact:
    redes_ipv6: "{{ lookup('file', '../../../files/redes_ipv6.csv') }}"

- name: Install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: latest
    update_cache: yes

- name: config interface
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: "{{ item.From }}"
    line: "{{ item.To }}"
  with_items:
    - { From: '^INTERFACESv4', To: 'INTERFACESv4="{{ tasks_dhcp_interfaces }}"' }
    - { From: '^INTERFACESv6', To: 'INTERFACESv6="{{ tasks_dhcp_interfaces }}"' }

- name: copy dhcp_consumer.sh
  template:
    src: templates/dhcp_consumer.j2
    dest: /root/dhcp_consumer.sh
    mode: 0700
  when: tasks_dhcp_consumer

- name: roda script no cron
  cron:
    name: "dhcp consumer"
    job: "/root/dhcp_consumer.sh"
  when: tasks_dhcp_consumer

- name: copy dhcp_clean_leases.sh
  template:
    src: templates/dhcp_clean_leases.j2
    dest: /root/dhcp_clean_leases.sh
    mode: 0700

- name: roda script leases
  cron:
    name: "dhcp leases"
    minute: "0"
    hour: "2"
    job: "/root/dhcp_clean_leases.sh"

- name: copy dhcp6.conf.j2
  template:
    src: templates/dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
    mode: 0644

- name: add rede ipv4 in dhcp.conf
  blockinfile:
    path: /etc/dhcp/dhcpd.conf
    insertafter: "^# DHCP"
    block: |
      subnet 192.168.8.0 netmask 255.255.255.0 {
        range 192.168.8.10 192.168.8.200;
      }
  when: not tasks_dhcp_consumer

- name: create IPv6 lease file
  file:
    path: /var/lib/dhcp/dhcpd6.leases
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: restart dhcpd
  service:
    name: isc-dhcp-server
    state: restarted
