### Tasks Thiago
# tasks obrigatórias para todos servidores
- import_tasks: thiago/common.yml
- import_tasks: thiago/ssh.yml
- import_tasks: thiago/vars.yml

- import_tasks: thiago/msmtp.yml
  when: tasks_msmtp

- import_tasks: thiago/cups.yml
  when: tasks_cups

- import_tasks: thiago/entrypointbackup.yml
  when: tasks_entrypointbackup

- import_tasks: thiago/rsyslog.yml
  when: tasks_rsyslog

- import_tasks: thiago/ftp.yml
  when: tasks_ftp

### Mônica
- import_tasks: monica/django.yml
  when: tasks_django

- import_tasks: monica/ocsinventoryserver.yml
  when: tasks_ocsinventoryserver

### Ricardo
- import_tasks: ricardo/php.yml
  when: tasks_php

- import_tasks: ricardo/bind.yml
  when: tasks_bind

- import_tasks: ricardo/dhcp.yml
  when: tasks_dhcp

### Augusto
- import_tasks: augusto/nginxrevproxy.yml
  when: tasks_nginxrevproxy

- import_tasks: augusto/databases.yml
  when: tasks_databases

- import_tasks: augusto/drupal.yml
  when: tasks_drupal
