#- include: common.yml
#- include: ssh.yml
#- include: vars.yml

- include: cups.yml
  when: tasks_cups

- include: msmtp.yml
  when: tasks_msmtp

- include: php.yml
  when: tasks_php

- include: bind.yml
  when: tasks_bind

- include: django.yml
  when: tasks_django

- include: nginxrevproxy.yml
  when: tasks_nginxrevproxy

- include: freeradius.yml
  when: tasks_freeradius

- include: rsyslog.yml
  when: tasks_rsyslog

- include: entrypointbackup.yml
  when: tasks_entrypointbackup

- include: ftp.yml
  when: tasks_ftp

- include: dhcp.yml
  when: tasks_dhcp

- include: databases.yml
  when: tasks_databases

- include: drupal.yml
  when: tasks_drupal

- include: ocsinventoryserver.yml
  when: tasks_ocsinventoryserver