- name: Copia os arquivos de trabalho
  shell: "scp -r -P 4321 acesarfs@10.64.0.40:/home/acesarfs/projetos/pb_drupal /home/vagrant/"

- name: Extrai arquivos FILES compactados
  shell: "tar -xvzf /home/vagrant/pb_drupal/{{ item.split('.')[0] }}_files.tar.gz"
  args:
      chdir: "/home/vagrant/pb_drupal/"
  loop: "{{ sites }}"

- name: Extrai arquivos PRIVATE compactados
  shell: "tar -xvzf /home/vagrant/pb_drupal/{{ item.split('.')[0] }}_private.tar.gz"
  args:
      chdir: "/home/vagrant/pb_drupal/"
  loop: "{{ sites }}"

- name: Executa o dump no banco de dados do site
  shell: "mariadb -u{{ item.split('.')[0] }} -p{{ lookup('passwordstore', 'sti/servidores/mysql/'+item.split('.')[0]) }} -h{{ tasks_drupal_database }} {{ item.split('.')[0] }} < /home/vagrant/pb_drupal/{{ item.split('.')[0] }}_dump.sql"
  loop: "{{ sites }}"

- name: Copia a pasta FILES
  shell: "cp -ar /home/vagrant/pb_drupal/var/aegir/platforms/drupal8916a/web/sites/{{ item.split('.')[0] }}.fflch.usp.br/files/ {{ tasks_drupal_dest }}/web/sites/{{ item }}/"
  loop: "{{ sites }}"

- name: Copia a pasta PRIVATE
  shell: "cp -ar /home/vagrant/pb_drupal/var/aegir/platforms/drupal8916a/web/sites/{{ item.split('.')[0] }}.fflch.usp.br/private/ {{ tasks_drupal_dest }}/web/sites/{{ item }}/"
  loop: "{{ sites }}"

- name: Atualiza os bancos de dados dos sites
  command: >-
    {{ tasks_drupal_dest }}/vendor/bin/drush updb {{ item }} -y
  args:
      chdir: "{{ tasks_drupal_dest }}/web/sites/{{ item }}"
  loop: "{{ sites }}"

- name: Atualiza as entidades dos sites
  command: >-
    {{ tasks_drupal_dest }}/vendor/bin/drush entup {{ item }} -y
  args:
      chdir: "{{ tasks_drupal_dest }}/web/sites/{{ item }}"
  loop: "{{ sites }}"