- name: Instala PHP versions
  include_role:
    name: geerlingguy.php-versions
  vars:
    php_version: "{{tasks_php_version}}"

- name: Instala PHP
  include_role:
    name: geerlingguy.php
  vars:
    php_default_version_debian: "{{tasks_php_version}}"
    php_version: "{{php_default_version_debian}}"
    php_packages_extra:
      - memcached
      - msmtp
      - php{{ php_default_version_debian }}-mbstring
      - php{{ php_default_version_debian }}-curl
      - php{{ php_default_version_debian }}-ldap
      - php{{ php_default_version_debian }}-bcmath
      - php{{ php_default_version_debian }}-pgsql
      - php{{ php_default_version_debian }}-mysql
      - php{{ php_default_version_debian }}-sqlite3
      - php{{ php_default_version_debian }}-sybase
      - php{{ php_default_version_debian }}-memcached
      - php{{ php_default_version_debian }}-xml
      - php{{ php_default_version_debian }}-gd
      - php{{ php_default_version_debian }}-zip
      - php{{ php_default_version_debian }}-intl
      - php{{ php_default_version_debian }}-xmlrpc
      - php{{ php_default_version_debian }}-soap
    # https://github.com/geerlingguy/ansible-role-php/blob/master/defaults/main.yml
    php_memory_limit: "1024M"
    php_max_execution_time: "300"
    php_max_input_time: "240"
    php_sendmail_path: "/usr/bin/msmtp -t"
    php_upload_max_filesize: "128M"
    php_max_file_uploads: "60"
    php_date_timezone: "America/Sao_Paulo"
    php_max_input_vars: "2000"
    php_post_max_size: "128M"

- name: Instalação do apache
  include_role:
    name: geerlingguy.apache
  vars:
    apache_create_vhosts: false
    apache_remove_default_vhost: false
    apache_mods_enabled:
      - rewrite
      - ssl

- name: index.html para virtualhost 000-default
  copy:
    dest: "/var/www/html/index.html"
    content: |
      <!DOCTYPE html>
      <html>
      <body><p>Servidor de Sistemas</p></body>
      </html> 

- include_role:
    name: geerlingguy.composer
  vars:
    composer_keep_updated: False
    composer_version_branch: '--2'

- name: Update repositories cache and install "libapache2-mod-php" package
  apt:
    name: "libapache2-mod-php{{tasks_php_version}}"
    update_cache: yes

- name: install ldap-utils
  apt:
    name: ldap-utils
    state: present
    update_cache: True

- name: Ensure directory /etc/ldap/ exists
  ansible.builtin.file:
    path: /etc/ldap/
    state: directory

- name: Em ambiente dev configura para não usar certificado no ldap
  shell: echo "TLS_REQCERT ALLOW" > /etc/ldap/ldap.conf

- name: memcached
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^I'
    line: 'I = 5M'

- name: replace text size in freetds - problema do php com sybase
  lineinfile:
    path: /etc/freetds/freetds.conf
    regexp: '[\t]text size'
    line: '\ttext size = 12902400'
    backrefs: yes

- name: php cli unlimited
  lineinfile:
    path: /etc/php/{{tasks_php_version}}/cli/php.ini
    regexp: 'memory_limit'
    line: 'memory_limit = -1'
    backrefs: yes
