- name: várias genéricas para roles de serviço
  set_fact:

    backup_user: 'root'
    backup_path: '/root/backups'
    backup_remote_host_name: 'cloud.fflch.usp.br'
    backup_remote_connection: root@cloud.fflch.usp.br
    backup_remote_connection_ssh_options: '-p 47119'
    backup_remote_base_path: "/backupsfflch" 
    backup_identifier: "{{ inventory_hostname }}"

    rsyslog_remote: 143.107.72.188
    rsyslog_config_file_format: advanced
    rsyslog_receiver: no # no servidor rsyslog temos que fazer o oposto